/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class InfGestionEncuesta extends javax.swing.JInternalFrame {

    /**
     * Creates new form InfGestionEncuestaGeneral
     */
    
    private DefaultTableModel defaultTableModel;
    public InfGestionEncuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblSeleccionePreguntas = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPreguntas = new javax.swing.JTable();
        btnRegistrarEncuesta = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        cbxCreacionPeriodoEncuesta = new javax.swing.JComboBox();
        btnModificarEncuesta = new javax.swing.JButton();
        btnListarPreguntas = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabelTipo = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextAreaQuestion = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTablePregunta1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButtonRegistrarPregunta = new javax.swing.JButton();
        jButtonListarPregunta = new javax.swing.JButton();
        jButtonModificarPregunta = new javax.swing.JButton();
        txtTipo = new javax.swing.JTextField();
        jLabelTipo1 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txaPregunta = new javax.swing.JTextArea();
        lblFormularPregunta = new javax.swing.JLabel();
        lblAniadirPreguntas = new javax.swing.JLabel();
        dtcFecha = new com.toedter.calendar.JDateChooser();
        lblSeleccioneEncuestaGeneral = new javax.swing.JLabel();
        cbxModificarEncuesta = new javax.swing.JComboBox();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblAsignaturas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAceptarAniadirPregunta = new javax.swing.JButton();
        lblMensajeAceptarAniadirPregunta = new javax.swing.JLabel();
        btnAniadirPregunta = new javax.swing.JButton();
        btnAceptarEncuesta = new javax.swing.JButton();
        btnListarAsignaturas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbxCaracteristica = new javax.swing.JComboBox();
        btnReiniciarVentana = new javax.swing.JButton();
        lblMensajeEncuesta = new javax.swing.JLabel();
        lblMensajeFecha = new javax.swing.JLabel();
        lblMensajeCaracteristicaPregunta = new javax.swing.JLabel();
        lblMensajePeriodo = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblMensajeTipoAniadir = new javax.swing.JLabel();
        lblMensajePreguntaAniadir = new javax.swing.JLabel();
        lblMensajePreguntaTabla = new javax.swing.JLabel();
        lblMensajeAsignaturaTabla = new javax.swing.JLabel();
        lblMensajeAceptarRegistroEncuesta = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblHabilitarEncuesta = new javax.swing.JLabel();
        cbxEncuestaHeg = new javax.swing.JComboBox();
        lblSeleccioneEncuesta = new javax.swing.JLabel();
        btnHabilitarHeg = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblAsignaturasHeg = new javax.swing.JTable();
        btnListarAsignaturasHeg = new javax.swing.JButton();
        bntAceptarHeg = new javax.swing.JButton();
        lblMensajeAceptarHeg = new javax.swing.JLabel();
        lblMensajeSeleccioneEncuestaHeg = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblTituloHabilitarEncuestas = new javax.swing.JLabel();
        lblSeleccioneEncuesta1 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tblEncuestasHee = new javax.swing.JTable();
        btnAceptarHee = new javax.swing.JButton();
        btnListarEncuestasHee = new javax.swing.JButton();
        btnHabilitarHee = new javax.swing.JButton();
        lblMensajeAceptarHee = new javax.swing.JLabel();

        setClosable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(1216, 615));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Crear Encuesta Con Preguntas General/Especial");

        lblSeleccionePreguntas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSeleccionePreguntas.setText("Seleccione Preguntas de la Tabla:");

        tblPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pregunta", "Tipo", "Seleccione"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPreguntasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPreguntas);

        btnRegistrarEncuesta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistrarEncuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoRegistrar.png"))); // NOI18N
        btnRegistrarEncuesta.setText("CREAR ENCUESTA");
        btnRegistrarEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEncuestaActionPerformed(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFecha.setText("Fecha De Creacion:");

        lblPeriodo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPeriodo.setText("Periodo De Creacion:");

        btnModificarEncuesta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificarEncuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoModificar.png"))); // NOI18N
        btnModificarEncuesta.setText("MODIFICAR ENCUESTA");
        btnModificarEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEncuestaActionPerformed(evt);
            }
        });

        btnListarPreguntas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListarPreguntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoMostrarInformacion.png"))); // NOI18N
        btnListarPreguntas.setText("LISTAR PREGUNTAS");
        btnListarPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPreguntasActionPerformed(evt);
            }
        });

        jInternalFrame1.setPreferredSize(new java.awt.Dimension(1226, 610));

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipo.setText("Tipo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Question :");

        jTextAreaQuestion.setColumns(20);
        jTextAreaQuestion.setRows(5);
        jScrollPane9.setViewportView(jTextAreaQuestion);

        jTablePregunta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Question", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePregunta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePregunta1MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jTablePregunta1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Registrar  Preguntas");

        jCheckBox1.setText("Crear Preguntas En General");

        jCheckBox2.setText("Crear Preguntas Especiales");

        jButtonRegistrarPregunta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRegistrarPregunta.setText("REGISTRAR");
        jButtonRegistrarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPreguntaActionPerformed(evt);
            }
        });

        jButtonListarPregunta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonListarPregunta.setText("LISTAR PREGUNTAS");
        jButtonListarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPreguntaActionPerformed(evt);
            }
        });

        jButtonModificarPregunta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonModificarPregunta.setText("MODIFICAR");
        jButtonModificarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarPreguntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabelTipo))
                                .addGap(41, 41, 41)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(123, 123, 123)
                                        .addComponent(jCheckBox1)
                                        .addGap(93, 93, 93)
                                        .addComponent(jCheckBox2))
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButtonRegistrarPregunta)
                        .addGap(108, 108, 108)
                        .addComponent(jButtonListarPregunta)
                        .addGap(110, 110, 110)
                        .addComponent(jButtonModificarPregunta))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipo)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox1))))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegistrarPregunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonModificarPregunta)
                        .addComponent(jButtonListarPregunta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTipo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipo1.setText("Tipo:");

        txaPregunta.setColumns(20);
        txaPregunta.setRows(5);
        jScrollPane11.setViewportView(txaPregunta);

        lblFormularPregunta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFormularPregunta.setText("Formular Pregunta:");

        lblAniadirPreguntas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAniadirPreguntas.setForeground(new java.awt.Color(255, 51, 51));
        lblAniadirPreguntas.setText("Añadir Pregunta a la Tabla");

        lblSeleccioneEncuestaGeneral.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSeleccioneEncuestaGeneral.setText(" Encuesta:");

        tblAsignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Asignatura", "Seleccione"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane12.setViewportView(tblAsignaturas);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Seleccione Las Asignaturas que  van Hacer Encuestadas: ");

        btnAceptarAniadirPregunta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptarAniadirPregunta.setText("ACEPTAR");

        btnAniadirPregunta.setBackground(new java.awt.Color(255, 255, 255));
        btnAniadirPregunta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAniadirPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoAdicionar.png"))); // NOI18N
        btnAniadirPregunta.setText("AÑADIR");
        btnAniadirPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirPreguntaActionPerformed(evt);
            }
        });

        btnAceptarEncuesta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptarEncuesta.setText("ACEPTAR");

        btnListarAsignaturas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListarAsignaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoMostrarInformacion.png"))); // NOI18N
        btnListarAsignaturas.setText("LISTAR ASIGNATURAS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Caracteristica De Pregunta:");

        btnReiniciarVentana.setBackground(new java.awt.Color(255, 255, 255));
        btnReiniciarVentana.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReiniciarVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoReiniciar.png"))); // NOI18N
        btnReiniciarVentana.setText("REINICIAR VENTANA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblAniadirPreguntas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12)
                            .addComponent(jScrollPane4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 228, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(251, 251, 251))
                            .addComponent(jLabel2)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblPeriodo)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dtcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxCreacionPeriodoEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 850, Short.MAX_VALUE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblMensajePeriodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                            .addComponent(lblMensajeFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblMensajeCaracteristicaPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblSeleccionePreguntas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMensajePreguntaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addComponent(btnAceptarEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarAsignaturas))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFormularPregunta)
                            .addComponent(jLabelTipo1))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMensajeTipoAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAniadirPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensajeAsignaturaTabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMensajePreguntaAniadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSeleccioneEncuestaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReiniciarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxModificarEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMensajeEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRegistrarEncuesta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addComponent(btnListarPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificarEncuesta)))))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addComponent(btnAceptarAniadirPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(lblMensajeAceptarAniadirPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(lblMensajeAceptarRegistroEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 169, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1047, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(907, 907, 907)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(lblFecha))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarEncuesta)
                            .addComponent(btnListarPreguntas)
                            .addComponent(btnRegistrarEncuesta)
                            .addComponent(btnReiniciarVentana))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtcFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbxModificarEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSeleccioneEncuestaGeneral)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensajeCaracteristicaPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensajeEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensajeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCreacionPeriodoEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPeriodo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMensajePeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lblSeleccionePreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMensajePreguntaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListarAsignaturas)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(lblMensajeAsignaturaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAceptarEncuesta)
                .addGap(21, 21, 21)
                .addComponent(lblMensajeAceptarRegistroEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblAniadirPreguntas)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelTipo1))
                            .addComponent(lblMensajeTipoAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAniadirPregunta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajePreguntaAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblFormularPregunta))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnAceptarAniadirPregunta)
                .addGap(2, 2, 2)
                .addComponent(lblMensajeAceptarAniadirPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 789, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 669, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(334, 334, 334)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1108, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1458, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("1.Crear Encuesta Con Preguntas General/Especial", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblHabilitarEncuesta.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblHabilitarEncuesta.setForeground(new java.awt.Color(255, 51, 51));
        lblHabilitarEncuesta.setText("Habilitar Encuesta Con Caracteristica De Preguntas General");

        cbxEncuestaHeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEncuestaHegActionPerformed(evt);
            }
        });

        lblSeleccioneEncuesta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSeleccioneEncuesta.setText("Seleccione Encuesta :");

        btnHabilitarHeg.setBackground(new java.awt.Color(255, 255, 255));
        btnHabilitarHeg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHabilitarHeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoHabilitar.png"))); // NOI18N
        btnHabilitarHeg.setText("HABILITAR ");
        btnHabilitarHeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarHegActionPerformed(evt);
            }
        });

        tblAsignaturasHeg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Encuesta General", "Codigo", "Asignatura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAsignaturasHeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAsignaturasHegMouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(tblAsignaturasHeg);

        btnListarAsignaturasHeg.setBackground(new java.awt.Color(255, 255, 255));
        btnListarAsignaturasHeg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListarAsignaturasHeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoMostrarInformacion.png"))); // NOI18N
        btnListarAsignaturasHeg.setText("LISTAR ASIGNATURAS DE ENCUESTA");

        bntAceptarHeg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bntAceptarHeg.setText("ACEPTAR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(bntAceptarHeg, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblSeleccioneEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHabilitarEncuesta)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cbxEncuestaHeg, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMensajeSeleccioneEncuestaHeg, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(155, 155, 155))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHabilitarHeg)
                                    .addComponent(btnListarAsignaturasHeg))))))
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(lblMensajeAceptarHeg, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHabilitarEncuesta)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxEncuestaHeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeleccioneEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHabilitarHeg)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMensajeSeleccioneEncuestaHeg, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnListarAsignaturasHeg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(bntAceptarHeg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeAceptarHeg, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("2. Habilitar Encuesta Con Caracteristica De Pregunta General", jPanel3);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloHabilitarEncuestas.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblTituloHabilitarEncuestas.setForeground(new java.awt.Color(255, 51, 51));
        lblTituloHabilitarEncuestas.setText(" Habilitar Encuesta Con Caracteristica De Preguntas Especial");

        lblSeleccioneEncuesta1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSeleccioneEncuesta1.setText("Seleccione Encuestas:");

        tblEncuestasHee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Encuesta Especial", "Codigo", "Asignatura", "Seleccione"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEncuestasHee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEncuestasHeeMouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(tblEncuestasHee);

        btnAceptarHee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptarHee.setText("ACEPTAR");
        btnAceptarHee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarHeeActionPerformed(evt);
            }
        });

        btnListarEncuestasHee.setBackground(new java.awt.Color(255, 255, 255));
        btnListarEncuestasHee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListarEncuestasHee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoMostrarInformacion.png"))); // NOI18N
        btnListarEncuestasHee.setText("LISTAR ENCUESTAS");
        btnListarEncuestasHee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarEncuestasHeeActionPerformed(evt);
            }
        });

        btnHabilitarHee.setBackground(new java.awt.Color(255, 255, 255));
        btnHabilitarHee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHabilitarHee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoHabilitar.png"))); // NOI18N
        btnHabilitarHee.setText("HABILITAR");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTituloHabilitarEncuestas)
                .addGap(146, 146, 146))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(lblSeleccioneEncuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(627, 627, 627)
                            .addComponent(btnListarEncuestasHee)
                            .addGap(18, 18, 18)
                            .addComponent(btnHabilitarHee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addComponent(btnAceptarHee, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(lblMensajeAceptarHee, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTituloHabilitarEncuestas)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblSeleccioneEncuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHabilitarHee, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListarEncuestasHee))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptarHee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeAceptarHee, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("3. Habilitar Encuestas Con Caracteristica De Pregunta Especial", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAsignaturasHegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAsignaturasHegMouseClicked

    }//GEN-LAST:event_tblAsignaturasHegMouseClicked

    private void btnHabilitarHegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarHegActionPerformed

    }//GEN-LAST:event_btnHabilitarHegActionPerformed

    private void cbxEncuestaHegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEncuestaHegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEncuestaHegActionPerformed

    private void btnListarEncuestasHeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarEncuestasHeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarEncuestasHeeActionPerformed

    private void btnAceptarHeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarHeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarHeeActionPerformed

    private void tblEncuestasHeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEncuestasHeeMouseClicked

    }//GEN-LAST:event_tblEncuestasHeeMouseClicked

    private void btnAniadirPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirPreguntaActionPerformed

    }//GEN-LAST:event_btnAniadirPreguntaActionPerformed

    private void jButtonModificarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarPreguntaActionPerformed

    }//GEN-LAST:event_jButtonModificarPreguntaActionPerformed

    private void jButtonListarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPreguntaActionPerformed

    }//GEN-LAST:event_jButtonListarPreguntaActionPerformed

    private void jButtonRegistrarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPreguntaActionPerformed

    }//GEN-LAST:event_jButtonRegistrarPreguntaActionPerformed

    private void jTablePregunta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePregunta1MouseClicked

    }//GEN-LAST:event_jTablePregunta1MouseClicked

    private void btnListarPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPreguntasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarPreguntasActionPerformed

    private void btnModificarEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEncuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarEncuestaActionPerformed

    private void btnRegistrarEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEncuestaActionPerformed

    }//GEN-LAST:event_btnRegistrarEncuestaActionPerformed

    private void tblPreguntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPreguntasMouseClicked

    }//GEN-LAST:event_tblPreguntasMouseClicked

    public JButton getBtnAceptarAniadirPregunta() {
        return btnAceptarAniadirPregunta;
    }

    public void setBtnAceptarAniadirPregunta(JButton btnAceptarAniadirPregunta) {
        this.btnAceptarAniadirPregunta = btnAceptarAniadirPregunta;
    }

    public JButton getBtnAceptarEncuesta() {
        return btnAceptarEncuesta;
    }

    public void setBtnAceptarEncuesta(JButton btnAceptarEncuesta) {
        this.btnAceptarEncuesta = btnAceptarEncuesta;
    }

    public JButton getBtnAceptarHabilitarEncuestas() {
        return btnAceptarHee;
    }

    public void setBtnAceptarHabilitarEncuestas(JButton btnAceptarHabilitarEncuestas) {
        this.btnAceptarHee = btnAceptarHabilitarEncuestas;
    }

    public JButton getBtnHabilitar() {
        return btnHabilitarHeg;
    }

    public void setBtnHabilitar(JButton btnHabilitar) {
        this.btnHabilitarHeg = btnHabilitar;
    }

    public JButton getBtnListarEncuestas() {
        return btnListarEncuestasHee;
    }

    public void setBtnListarEncuestas(JButton btnListarEncuestas) {
        this.btnListarEncuestasHee = btnListarEncuestas;
    }

    public JButton getBtnListarPreguntas() {
        return btnListarPreguntas;
    }

    public void setBtnListarPreguntas(JButton btnListarPreguntas) {
        this.btnListarPreguntas = btnListarPreguntas;
    }

    public JButton getBtnModificarEncuesta() {
        return btnModificarEncuesta;
    }

    public void setBtnModificarEncuesta(JButton btnModificarEncuesta) {
        this.btnModificarEncuesta = btnModificarEncuesta;
    }

    public JButton getBtnRegistrarEncuesta() {
        return btnRegistrarEncuesta;
    }

    public void setBtnRegistrarEncuesta(JButton btnRegistrarEncuesta) {
        this.btnRegistrarEncuesta = btnRegistrarEncuesta;
    }

    public JButton getBtnRegistrarPregunta() {
        return btnAniadirPregunta;
    }

    public void setBtnRegistrarPregunta(JButton btnRegistrarPregunta) {
        this.btnAniadirPregunta = btnRegistrarPregunta;
    }

    public JButton getBtnReiniciarVentana() {
        return btnReiniciarVentana;
    }

    public void setBtnReiniciarVentana(JButton btnReiniciarVentana) {
        this.btnReiniciarVentana = btnReiniciarVentana;
    }

    public JButton getBtnAniadirPregunta() {
        return btnAniadirPregunta;
    }

    public void setBtnAniadirPregunta(JButton btnAniadirPregunta) {
        this.btnAniadirPregunta = btnAniadirPregunta;
    }

    public JButton getBtnListarAsignaturas() {
        return btnListarAsignaturas;
    }

    public void setBtnListarAsignaturas(JButton btnListarAsignaturas) {
        this.btnListarAsignaturas = btnListarAsignaturas;
    }

    public JTable getTblAsignaturas() {
        return tblAsignaturas;
    }

    public void setTblAsignaturas(JTable tblAsignaturas) {
        this.tblAsignaturas = tblAsignaturas;
    }

    public JTable getTblPreguntas() {
        return tblPreguntas;
    }

    public void setTblPreguntas(JTable tblPreguntas) {
        this.tblPreguntas = tblPreguntas;
    }

    public JComboBox getCbxCaracteristica() {
        return cbxCaracteristica;
    }

    public void setCbxCaracteristica(JComboBox cbxCaracteristica) {
        this.cbxCaracteristica = cbxCaracteristica;
    }

   
   
    
    public DefaultTableModel getDefaultTableModel() {
        return defaultTableModel;
    }

    public void setDefaultTableModel(DefaultTableModel defaultTableModel) {
        this.defaultTableModel = defaultTableModel;
    }

    public JDateChooser getDtcFecha() {
        return dtcFecha;
    }

    public void setDtcFecha(JDateChooser dtcFecha) {
        this.dtcFecha = dtcFecha;
    }

    public JLabel getLblMensajeFecha() {
        return lblMensajeFecha;
    }

    public void setLblMensajeFecha(JLabel lblMensajeFecha) {
        this.lblMensajeFecha = lblMensajeFecha;
    }

    public JLabel getLblMensajePeriodo() {
        return lblMensajePeriodo;
    }

    public void setLblMensajePeriodo(JLabel lblMensajePeriodo) {
        this.lblMensajePeriodo = lblMensajePeriodo;
    }

    public JComboBox getCbxModificarEncuesta() {
        return cbxModificarEncuesta;
    }

    public void setCbxModificarEncuesta(JComboBox cbxModificarEncuesta) {
        this.cbxModificarEncuesta = cbxModificarEncuesta;
    }

    public JTextArea getTxaPregunta() {
        return txaPregunta;
    }

    public void setTxaPregunta(JTextArea txaPregunta) {
        this.txaPregunta = txaPregunta;
    }

    public JTextField getTxtTipo() {
        return txtTipo;
    }

    public void setTxtTipo(JTextField txtTipo) {
        this.txtTipo = txtTipo;
    }

    public JComboBox getCbxCreacionPeriodoEncuesta() {
        return cbxCreacionPeriodoEncuesta;
    }

    public void setCbxCreacionPeriodoEncuesta(JComboBox cbxCreacionPeriodoEncuesta) {
        this.cbxCreacionPeriodoEncuesta = cbxCreacionPeriodoEncuesta;
    }

    public JLabel getLblMensajeCaracteristicaPregunta() {
        return lblMensajeCaracteristicaPregunta;
    }

    public void setLblMensajeCaracteristicaPregunta(JLabel lblMensajeCaracteristicaPregunta) {
        this.lblMensajeCaracteristicaPregunta = lblMensajeCaracteristicaPregunta;
    } 

    public JLabel getLblMensajeTipoAniadir() {
        return lblMensajeTipoAniadir;
    }

    public void setLblMensajeTipoAniadir(JLabel lblMensajeTipoAniadir) {
        this.lblMensajeTipoAniadir = lblMensajeTipoAniadir;
    }

    public JLabel getLblMensajePreguntaAniadir() {
        return lblMensajePreguntaAniadir;
    }

    public void setLblMensajePreguntaAniadir(JLabel lblMensajePreguntaAniadir) {
        this.lblMensajePreguntaAniadir = lblMensajePreguntaAniadir;
    }

    public JLabel getLblMensajeAceptarAniadirPregunta() {
        return lblMensajeAceptarAniadirPregunta;
    }

    public void setLblMensajeAceptarAniadirPregunta(JLabel lblMensajeAceptarAniadirPregunta) {
        this.lblMensajeAceptarAniadirPregunta = lblMensajeAceptarAniadirPregunta;
    }

    public JLabel getLblMensajePreguntaTabla() {
        return lblMensajePreguntaTabla;
    }

    public void setLblMensajePreguntaTabla(JLabel lblMensajePreguntaTabla) {
        this.lblMensajePreguntaTabla = lblMensajePreguntaTabla;
    }

    public JLabel getLblMensajeAsignaturaTabla() {
        return lblMensajeAsignaturaTabla;
    }

    public void setLblMensajeAsignaturaTabla(JLabel lblMensajeAsignaturaTabla) {
        this.lblMensajeAsignaturaTabla = lblMensajeAsignaturaTabla;
    }

    public JLabel getLblMensajeAceptarRegistroEncuesta() {
        return lblMensajeAceptarRegistroEncuesta;
    }

    public void setLblMensajeAceptarRegistroEncuesta(JLabel lblMensajeAceptarRegistroEncuesta) {
        this.lblMensajeAceptarRegistroEncuesta = lblMensajeAceptarRegistroEncuesta;
    }

   
    
    
     public  boolean validarCamposGestionarEncuesta(){
          boolean blValidacion =true;
            if(getCbxCreacionPeriodoEncuesta().getSelectedIndex()==0){
               getLblMensajePeriodo().setText("Ingrese periodo de creación de la encuesta.");
               blValidacion =false;
            }            
            if(capturarPreguntasSeleccionadas()<10){
               getLblMensajePreguntaTabla().setText("Debe seleccionar mínimo 10 preguntas.");
               blValidacion =false;
            }
            if(capturarAsignaturasSeleccionadas()<1){
                getLblMensajeAsignaturaTabla().setText("Debe seleccionar las asignaturas para la encuesta.");
               blValidacion =false;
            }
            
            if(getDtcFecha().getDate()==null){
            
                getLblMensajeFecha().setText("Ingrese fecha de creación de la encuesta.");
                blValidacion =false;
            }          
       return blValidacion;
    }
     
    public int capturarAsignaturasSeleccionadas(){
        int inColumnaCheckBox = 2;
        boolean blEstadoCheckBox = false;
        int inContador = 0;
        
         for (int i = 0; i < getTblAsignaturas().getRowCount(); i++){ 
          
            if(getTblAsignaturas().getValueAt(i,inColumnaCheckBox)!=null){ 
                blEstadoCheckBox =(boolean) getTblAsignaturas().getValueAt(i,inColumnaCheckBox);
                if(blEstadoCheckBox){                  
                  inContador++;
                }                
            }                    
        }
       return inContador;
    }   
   public int capturarPreguntasSeleccionadas(){
        int inColumnaCheckBox = 2;
        boolean blEstadoCheckBox = false;
        int inContador = 0;
        
         for (int i = 0; i < getTblPreguntas().getRowCount(); i++){ 
           System.out.println(getTblPreguntas().getValueAt(i,inColumnaCheckBox)!=null);
            if(getTblPreguntas().getValueAt(i,inColumnaCheckBox)!=null){ 
                System.out.println("estado tabla:"+getTblPreguntas().getValueAt(i,inColumnaCheckBox));
                blEstadoCheckBox =(boolean) getTblPreguntas().getValueAt(i,inColumnaCheckBox);
                if(blEstadoCheckBox){                  
                  inContador++;
                }                
            }                    
        }
       return inContador;
    }  
     
    private  boolean validarCampoVacio(String stCampo){
        boolean blValidacion =false;
            if(stCampo.equals("")){
               blValidacion = true;
            }       
        return blValidacion;
     }
    public void limpiarTabla(JTable tabla){
        try {
            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
     
    /***********************************************Habilitar Encuesta Con Caracteristica De Preguntas General****************************/
    public JButton getBntAceptarHeg() {
        return bntAceptarHeg;
    }

    public void setBntAceptarHeg(JButton bntAceptarHeg) {
        this.bntAceptarHeg = bntAceptarHeg;
    }

    public JButton getBtnHabilitarHeg() {
        return btnHabilitarHeg;
    }

    public void setBtnHabilitarHeg(JButton btnHabilitarHeg) {
        this.btnHabilitarHeg = btnHabilitarHeg;
    }

    public JButton getBtnListarAsignaturasHeg() {
        return btnListarAsignaturasHeg;
    }

    public void setBtnListarAsignaturasHeg(JButton btnListarAsignaturasHeg) {
        this.btnListarAsignaturasHeg = btnListarAsignaturasHeg;
    }

    public JComboBox getCbxEncuestaHeg() {
        return cbxEncuestaHeg;
    }

    public void setCbxEncuestaHeg(JComboBox cbxEncuestaHeg) {
        this.cbxEncuestaHeg = cbxEncuestaHeg;
    }

    public JLabel getLblMensajeAceptarHeg() {
        return lblMensajeAceptarHeg;
    }

    public void setLblMensajeAceptarHeg(JLabel lblMensajeAceptarHeg) {
        this.lblMensajeAceptarHeg = lblMensajeAceptarHeg;
    }

    

    

    public JLabel getLblMensajeSeleccioneEncuestaHeg() {
        return lblMensajeSeleccioneEncuestaHeg;
    }

    public void setLblMensajeSeleccioneEncuestaHeg(JLabel lblMensajeSeleccioneEncuestaHeg) {
        this.lblMensajeSeleccioneEncuestaHeg = lblMensajeSeleccioneEncuestaHeg;
    }

  
    public JTable getTblAsignaturasHeg() {
        return tblAsignaturasHeg;
    }

    public void setTblAsignaturasHeg(JTable tblAsignaturasHeg) {
        this.tblAsignaturasHeg = tblAsignaturasHeg;
    }
    
    
    public  boolean validarCamposHabilitarEncuestaGeneral(){
          boolean blValidacion =true;
            if(getCbxEncuestaHeg().getSelectedIndex()==0){
               getLblMensajeSeleccioneEncuestaHeg().setText("Seleccione la Encuesta.");
               blValidacion =false;
            }  
            
                     
       return blValidacion;
    }
     
    /* **************************   Habilitar Encuesta Con Caracteristica De Preguntas Especial***************************/
    public JButton getBtnHabilitarHee() {
        return btnHabilitarHee;
    }

    public void setBtnHabilitarHee(JButton btnHabilitarHee) {
        this.btnHabilitarHee = btnHabilitarHee;
    }
    

    public JButton getBtnListarEncuestasHee() {
        return btnListarEncuestasHee;
    }

    public void setBtnListarEncuestasHee(JButton btnListarEncuestasHee) {
        this.btnListarEncuestasHee = btnListarEncuestasHee;
    }

    

    public JTable getTblEncuestasHee() {
        return tblEncuestasHee;
    }

    public void setTblEncuestasHee(JTable tblEncuestasHee) {
        this.tblEncuestasHee = tblEncuestasHee;
    }

    public JButton getBtnAceptarHee() {
        return btnAceptarHee;
    }

    public void setBtnAceptarHee(JButton btnAceptarHee) {
        this.btnAceptarHee = btnAceptarHee;
    }

    public JLabel getLblMensajeAceptarHee() {
        return lblMensajeAceptarHee;
    }

    public void setLblMensajeAceptarHee(JLabel lblMensajeAceptarHee) {
        this.lblMensajeAceptarHee = lblMensajeAceptarHee;
    }

    
    
    

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAceptarHeg;
    private javax.swing.JButton btnAceptarAniadirPregunta;
    private javax.swing.JButton btnAceptarEncuesta;
    private javax.swing.JButton btnAceptarHee;
    private javax.swing.JButton btnAniadirPregunta;
    private javax.swing.JButton btnHabilitarHee;
    private javax.swing.JButton btnHabilitarHeg;
    private javax.swing.JButton btnListarAsignaturas;
    private javax.swing.JButton btnListarAsignaturasHeg;
    private javax.swing.JButton btnListarEncuestasHee;
    private javax.swing.JButton btnListarPreguntas;
    private javax.swing.JButton btnModificarEncuesta;
    private javax.swing.JButton btnRegistrarEncuesta;
    private javax.swing.JButton btnReiniciarVentana;
    private javax.swing.JComboBox cbxCaracteristica;
    private javax.swing.JComboBox cbxCreacionPeriodoEncuesta;
    private javax.swing.JComboBox cbxEncuestaHeg;
    private javax.swing.JComboBox cbxModificarEncuesta;
    private com.toedter.calendar.JDateChooser dtcFecha;
    private javax.swing.JButton jButtonListarPregunta;
    private javax.swing.JButton jButtonModificarPregunta;
    private javax.swing.JButton jButtonRegistrarPregunta;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePregunta1;
    private javax.swing.JTextArea jTextAreaQuestion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JLabel lblAniadirPreguntas;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFormularPregunta;
    private javax.swing.JLabel lblHabilitarEncuesta;
    private javax.swing.JLabel lblMensajeAceptarAniadirPregunta;
    private javax.swing.JLabel lblMensajeAceptarHee;
    private javax.swing.JLabel lblMensajeAceptarHeg;
    private javax.swing.JLabel lblMensajeAceptarRegistroEncuesta;
    private javax.swing.JLabel lblMensajeAsignaturaTabla;
    private javax.swing.JLabel lblMensajeCaracteristicaPregunta;
    private javax.swing.JLabel lblMensajeEncuesta;
    private javax.swing.JLabel lblMensajeFecha;
    private javax.swing.JLabel lblMensajePeriodo;
    private javax.swing.JLabel lblMensajePreguntaAniadir;
    private javax.swing.JLabel lblMensajePreguntaTabla;
    private javax.swing.JLabel lblMensajeSeleccioneEncuestaHeg;
    private javax.swing.JLabel lblMensajeTipoAniadir;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblSeleccioneEncuesta;
    private javax.swing.JLabel lblSeleccioneEncuesta1;
    private javax.swing.JLabel lblSeleccioneEncuestaGeneral;
    private javax.swing.JLabel lblSeleccionePreguntas;
    private javax.swing.JLabel lblTituloHabilitarEncuestas;
    private javax.swing.JTable tblAsignaturas;
    private javax.swing.JTable tblAsignaturasHeg;
    private javax.swing.JTable tblEncuestasHee;
    private javax.swing.JTable tblPreguntas;
    private javax.swing.JTextArea txaPregunta;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
